### ISSUE TITLE
Ignoring config settings.

### ISSUE THREAD

**Issue by cqrt** [ociviol/cbzManager#4]
This version seems faster than 1.0.1.12 but it seems to be ignoring some config settings.

Filename Cleaner - 'Remove Dashes (-)' setting is ignored. CBZ Manager will delete dashes regardless of the setting. The other options i.e Remove Dots, Parenthesis etc, seem to work fine.

Config - 'Delete file after convert' will leave the old file backup in place regardless of this setting.

Windows 10
CBZManagerWin 1.0.1.84 x64

**Comment by ociviol** [comment]
Fixed
