### ISSUE TITLE
Brew unrar:  No formula or cask with the name "unrar" (OSX)

### ISSUE THREAD

**Issue by solidus0079** [ociviol/cbzManager#6]
Warning: No available formula or cask with the name "unrar". Did you mean unar?
==> Searching for similarly named formulae...
This similarly named formula was found:
unar 
To install it, run:
  brew install unar 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by ociviol** [comment]
hi,

it's not in brew any more, but it's there : https://github.com/ociviol/cbzManager/tree/master/cbzManager/Bin-Mac

Cordialement - Best Regards
Email/Skype : ***@***.***

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by solidus0079** [comment]
Ok, good to know.  I can't find anything in any of the help files what to do with it though, all I see are references to the outmoded Brew install.  Appreciate the help :)

**Comment by ociviol** [comment]
copy the unbar application to /usr/local/bin/unrar

Cordialement - Best Regards
Email/Skype : ***@***.***

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
